apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wavemaker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wavemaker.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  # Read
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # Write
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete"]